### PR TITLE
feat(conn-handshake): ConnectionOpenTry from Cosmos to Sovereign

### PR DESCRIPTION
**Pull request by rnbguy**
Closes: #248 

## Description

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by rnbguy** [comment]
Currently the test fails because there is no client created at Sovereign rollup.

**Comment by soareschen** [comment]
We need to merge both cosmos-to-sovereign and sovereign-to-cosmos tests. For now you can copy the code from `test_cosmos_to_sovereign` to create the client on Sovereign:

```rust

            let client_id = CosmosToSovereignRelay::create_client(
                DestinationTarget,
                &sovereign_chain,
                cosmos_chain,
                &create_client_settings,
            )
            .await?;
```

**Comment by rnbguy** [comment]
Now the test fails because the Cosmos ConnectionOpenTry payload builder expects a Tendermint ClientState - but the Sovereign light client has a Wasm client type.

**Comment by soareschen** [comment]
> Now the test fails because the Cosmos ConnectionOpenTry payload builder expects a Tendermint ClientState - but the Sovereign light client has a Wasm client type.

Which direction are you building the `ConnectionOpenTry` message? If you build the payload on the CosmosChain, it would query the client state from Sovereign, which should be of `TendermintClientState` type.

**Comment by soareschen** [comment]
I think I know the issue. We need to refactor the connection handshake payload builder at `crates/cosmos/cosmos-chain-components/src/impls/connection/connection_handshake_payload.rs` to not depend on `ChainHandle`. This is because `ChainHandle` does not know about the SovereignClientState, hence the error.

The `CosmosConnectionOpenTryPayload` type also needs to be generalized so that it does not contain TendermintClientState directly.

**Comment by soareschen** [comment]
Let's comment out the test failure and get this merged first.

**Comment by rnbguy** [comment]
@soareschen, thanks for the suggestions :slightly_smiling_face: I have commented on the connection payload creation part at Cosmos. You can merge the PR if everything else looks good :raised_hands:

**Pull request merged**
